security:
  oauth2:
    client:
      clientId: <CLIENT_ID>
      clientSecret: <CLIENT_SECRET>
      accessTokenUri: https://graph.facebook.com/v3.0/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/v3.0/dialog/oauth
      redirectUri: localhost:8080/redirect
      tokenName: access_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: email
    resource:
      userInfoUri: https://graph.facebook.com/me